### ISSUE TITLE
sign in

### ISSUE THREAD

**Issue by moh1122** [mownier/photostream#1]
Hello
After creating google-info.plist i run the app but i cant create new user?

**Comment by jteri3** [comment]
Hi,
What security rules setup is needed for database and storage? Also, how do you post a new photo?

**Comment by mownier** [comment]
Currently, the register view controller is not yet being called from the login view controller. The features are not yet all connected.

Regarding with the rules, the default rule is ok. Posting is not yet implemented.

**Comment by jteri3** [comment]
Okay, thanks for the update!

**Comment by mownier** [comment]
**UPDATE**: user can now sign in, register, and post photo. :)
