### ISSUE TITLE
iOS11 and Swift 4 Support

### ISSUE THREAD

**Issue by kronik** [mownier/photostream#4]
Hi! Are you planning to add any iOS11 and/or Swift4 support?

**Comment by mownier** [comment]
yes, i will update it to iOS 11 and Swift4

**Comment by hcrgithub** [comment]
Can you please let us know by when you think you will be completed with Swift 4 support?

**Comment by mownier** [comment]
Updated to iOS 11 and Swift 4. Check out the master branch. If you wish to stay on Swift 3, there is a swift3 branch for that.
