### ISSUE TITLE
it is not allowing the to store the post and show in the news feed

### ISSUE THREAD

**Issue by umair-shams** [mownier/photostream#7]
Hi...
When i write the post after selecting photo and then click on done button then nothing happens. It is showing a little selecting image with progress and nothing happen i have wait 10 minuts. Users are storing but post and photo are not storing. I think it has the storage issue may be firbase storage link reference in the project is wrong   but i could not find any firebase storage link in the project..
Please solve this problem and guide me.
see the attach file
![simulator screen shot - iphone 6s - 2018-05-20 at 17 42 23](https://user-images.githubusercontent.com/24223877/40279105-577e9c32-5c56-11e8-8fe1-c3184ed623b8.png)

**Comment by mownier** [comment]
Do you have already the `GoogleService-Info.plist` file?

**Comment by umair-shams** [comment]
Yes bro i have ..
Users are creating during sign up

**Comment by umair-shams** [comment]
I like this project.. Please tell me what can be the problem

**Comment by mownier** [comment]
Can you debug the code in the `FileServiceProvider.swift` file?

**Comment by umair-shams** [comment]
wait i show you the error... something prints

**Comment by umair-shams** [comment]
this is my GoogleService-info.plist

**Comment by umair-shams** [comment]
see the highlighted area

**Comment by umair-shams** [comment]
please check also firebase database and storage rules in the below screen
shots

**Comment by umair-shams** [comment]
bro i change the storage rules post is working

**Comment by umair-shams** [comment]
bro on more thing i want to ask you.. how to show notification on heart ...
when someone follow you or like or commented your pots ??

**Comment by mownier** [comment]
I'm gonna close this since posting is now working. Regarding with the notification, you can look into iOS push notification or Firebase's observe methods.

**Comment by umair-shams** [comment]
OK thanks

**Comment by umair-shams** [comment]
do you have e-commerce type of app on github ?
